server:
  port: 80
  servlet: "*.do"
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/qinglan?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: system
mybatis:
  type-aliases-package: com.qinglan.pojo
